### ISSUE TITLE
Basic comments at start of file do not parse correctly

### ISSUE THREAD

**Issue by chriskrycho** [kylegoetz/tree-sitter-unison#46]
I have done zero debugging other than consistently seeing this in Nova, so it is *possible* if unlikely?) that it is a bug in Nova, but this simple test case should do the trick to find out: just start a file with this—

```unison
-- this is a comment
```

At least in Nova's use of the parser, it parses as an operator instead of a comment start. Regular doc blocks and all other items I have tried parse correctly in that position, though.

**Comment by kylegoetz** [comment]
Thanks for spotting this!

It's indeed a bug on my end. Since a comment can appear anywhere, normally what happens is the parser will spot a comment on its own line as something that exists at the very end of whatever structure was just discovered (i.e., a type declaration, term declaration, or use clause, in the case of top-level).

You've discovered a bug where when the first thing in a file is a comment, the code path attempts to parse it as a fold, notices the lack of a third "-", and then fails to try a comment at all.

Fix was to have the `fold` parser fork off if there is "--" but not "---" and parse as line comment

**Comment by chriskrycho** [comment]
Thanks for the quick fix!

**Comment by kylegoetz** [comment]
No problem! It makes me very happy to have bug fixes someone else has reported instead of me reporting them.
